# alpaca eval is
alpaca_eval_gpt4.1:
  prompt_template: "alpaca_eval_gpt4.1/alpaca_eval.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    # model_name: "gpt-4o"
    model_name: "gpt-4.1"
    max_tokens: 100
    temperature: 0
  fn_completion_parser: "ranking_parser"
  batch_size: 1
